class FBTABrowserConstant:
    SIGNAL_NORMAL_START = -2
    SIGNAL_NORMAL = -1
    TITLE_LOGINAGIN = 0
    TITLE_RESTART = 1
    TITLE_DOING_CHECKONLYTITLE = 2
    TITLE_DOING_CHECKONLYCONTENT = 3

    FBSCOPE_PRIVATE = 0
    FBSCOPE_GLOBAL = 1

    NODE_MASTER = 'node_master'
    NODE_SLAVE = 'node_slave'
