class FBTABrowserConstant:
    STATUS_SAVE_AND_IGNORE = 'STATUS_SAVE_AND_IGNORE'
    DEBUG = 'debug'
    DEBUG_SHOW_SOURCE = 'debug_show_source'
    SIGNAL_NORMAL_START = -2
    SIGNAL_NORMAL = -1

    DOING_TITLE_CHECK_ONLY = 'DOING_CHECK_ONLY_TITLE'
    DOING_CONTENT_CHECK_ONLY = 'DOING_CHECK_ONLY_CONTENT'

    STATUS_CONTENT_RELOAD = 5
    STATUS_CONTENT_RELOAD_ONCE = 6
    STATUS_LOGIN_AGAIN = 98
    STATUS_BROWSER_RESTART = 99
    STATUS_DO_NOTHING = -99

    STATUS_NORMAL = STATUS_DO_NOTHING

    FBSCOPE_PRIVATE = 0
    FBSCOPE_GLOBAL = 1

    NODE_MASTER = 'node_master'
    NODE_SLAVE = 'node_slave'
